// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Services.ProductAPI.Data;

#nullable disable

namespace Store.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("bd2c9258-ee9c-4f8b-83ae-5a3e6e00cb87"),
                            CategoryName = "Tennis",
                            Description = "Hard Court Tennis Shoes",
                            ImageUrl = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/733b75de-1ebc-4842-baad-2035b1d5e4e2/M+NIKE+ZOOM+VAPOR+11+HC.png",
                            Name = "NikeCourt Air Zoom Vapor 11",
                            Price = 170.0
                        },
                        new
                        {
                            ProductId = new Guid("9175c962-250a-40cd-aa3d-832d9e555b6d"),
                            CategoryName = "Tennis",
                            Description = "Hard Court Tennis Shoes",
                            ImageUrl = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/533dfb67-8c51-4ace-ac1e-ba51f1ac7766/W+ZOOM+GP+CHALLENGE+1+HC.png",
                            Name = "Nike Zoom GP Challenge 1",
                            Price = 160.0
                        },
                        new
                        {
                            ProductId = new Guid("2bb2d3cd-c94d-4085-9bfa-c2b5739b57b1"),
                            CategoryName = "Tennis",
                            Description = "Pickleball shoes",
                            ImageUrl = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e1e4ff2e-7111-419d-8165-7874d8e4846b/M+ZOOM+CHALLENGE+PB.png",
                            Name = "Nike Zoom Challenge",
                            Price = 120.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
